# Generated by Django 3.1.7 on 2021-05-21 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=100)),
                ('batch_year', models.CharField(max_length=100)),
                ('batch_month', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'batch',
            },
        ),
        migrations.CreateModel(
            name='career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('discription', models.CharField(max_length=100)),
                ('file', models.CharField(max_length=100)),
                ('lastdate', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'career',
            },
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('discription', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=100)),
                ('discrption', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'enquiry',
            },
        ),
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultyname', models.CharField(max_length=100)),
                ('gender', models.CharField(default='male', max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=100)),
                ('experience', models.CharField(default='na', max_length=100)),
                ('qualifiction', models.CharField(default='na', max_length=100)),
                ('image', models.CharField(max_length=200)),
                ('house_name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'faculty',
            },
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('user_type', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'login',
            },
        ),
        migrations.CreateModel(
            name='work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discrption', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('BATCH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_market_institute_managment_system.batch')),
                ('FACULTY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_market_institute_managment_system.faculty')),
            ],
            options={
                'db_table': 'work',
            },
        ),
        migrations.CreateModel(
            name='syllabus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.CharField(max_length=200)),
                ('COURSE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_market_institute_managment_system.course')),
            ],
            options={
                'db_table': 'syllabus',
            },
        ),
        migrations.CreateModel(
            name='studymaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.CharField(max_length=200)),
                ('date', models.DateField(max_length=100)),
                ('COURSE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_market_institute_managment_system.course')),
                ('FACULTY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_market_institute_managment_system.faculty')),
            ],
            options={
                'db_table': 'studymaterial',
            },
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=100)),
                ('housename', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('BATCH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_market_institute_managment_system.batch')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_market_institute_managment_system.login')),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('FACULTY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_market_institute_managment_system.faculty')),
            ],
            options={
                'db_table': 'salary',
            },
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('review', models.CharField(max_length=100)),
                ('COURSE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_market_institute_managment_system.course')),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_market_institute_managment_system.student')),
            ],
            options={
                'db_table': 'review',
            },
        ),
        migrations.CreateModel(
            name='facultyattedence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('FACULTY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_market_institute_managment_system.faculty')),
            ],
            options={
                'db_table': 'facultyattedence',
            },
        ),
        migrations.AddField(
            model_name='faculty',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_market_institute_managment_system.login'),
        ),
        migrations.CreateModel(
            name='exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('starting_date', models.CharField(max_length=100)),
                ('discrption', models.CharField(max_length=100)),
                ('BATCH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_market_institute_managment_system.batch')),
            ],
            options={
                'db_table': 'exam',
            },
        ),
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=100)),
                ('FACULTY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_market_institute_managment_system.faculty')),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_market_institute_managment_system.student')),
            ],
            options={
                'db_table': 'chat',
            },
        ),
        migrations.CreateModel(
            name='batchassign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('BATCH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_market_institute_managment_system.batch')),
                ('FACULTY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_market_institute_managment_system.faculty')),
            ],
            options={
                'db_table': 'batchassign',
            },
        ),
        migrations.AddField(
            model_name='batch',
            name='COURSE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_market_institute_managment_system.course'),
        ),
        migrations.CreateModel(
            name='attendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_market_institute_managment_system.student')),
            ],
            options={
                'db_table': 'attendence',
            },
        ),
        migrations.CreateModel(
            name='archiement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('file', models.CharField(max_length=100)),
                ('name', models.CharField(default='na', max_length=100)),
                ('discription', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_market_institute_managment_system.student')),
            ],
            options={
                'db_table': 'archiement',
            },
        ),
        migrations.CreateModel(
            name='application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('CAREER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_market_institute_managment_system.career')),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_market_institute_managment_system.student')),
            ],
            options={
                'db_table': 'application',
            },
        ),
    ]
